apiVersion: v1
kind: Service
metadata:
  name: galera-rs
  namespace: production
  labels:
    app: galera-rs
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 3306
  selector:
    app: galera
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: galera
  labels:
    app: galera
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: galera
    spec:
      containers:
      - name: galera

        image: severalnines/mariadb:10.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: qwerty
        - name: DISCOVERY_SERVICE
          value: etcd-client:2379
        - name: XTRABACKUP_PASSWORD
          value: qwerty
        - name: CLUSTER_NAME
          value: galera_ma
        - name: MYSQL_DATABASE
          value: Wordpress
        - name: MYSQL_USER
          value: tester
        - name: MYSQL_PASSWORD
          value: qwerty
        ports:
        - name: mysql
          containerPort: 3306
        readinessProbe:
          exec:
           command:
            - /healthcheck.sh
            - --readiness
          initialDelaySeconds: 120
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --liveness
          initialDelaySeconds: 120
          periodSeconds: 1
