---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
    purpose: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      purpose: example
  template:
    metadata:
      labels:
        app: prometheus
        purpose: example
    spec:
      containers:
      - name: prometheus-example
        image: prom/prometheus
        #command: [ "/bin/sh", "-c", "ls /etc/prometheus/" ]
        # Just spin & wait forever
        #command: [ "/bin/sh", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
        ports:
        - containerPort: 9090
      volumes:
        - name: config-volume
          configMap:
           name: prometheus-cm
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-example-service
spec:
  selector:
    app: prometheus
    purpose: example
  type: LoadBalancer
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090