---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: pavlomysiuk/first
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "web2"
---
apiVersion: v1
kind: Service
metadata:
  name: web2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web2
