apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2018-10-29T17:26:20Z
  generation: 2
  labels:
    app: exporter-kube-state
    chart: exporter-kube-state-0.2.6
    component: kube-state
    heritage: Tiller
    release: kube-prometheus
    version: v1.2.0
  name: kube-prometheus-exporter-kube-state
  namespace: monitoring
  resourceVersion: "4635"
  selfLink: /apis/extensions/v1beta1/namespaces/monitoring/deployments/kube-prometheus-exporter-kube-state
  uid: bff16030-db9f-11e8-868c-b26230958cf1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-prometheus-exporter-kube-state
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-prometheus-exporter-kube-state
        component: kube-state
        release: kube-prometheus
        version: v1.2.0
    spec:
      containers:
      - image: gcr.io/google_containers/kube-state-metrics:v1.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: exporter-kube-state
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 101m
            memory: 132Mi
          requests:
            cpu: 101m
            memory: 132Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /pod_nanny
        - --container=exporter-kube-state
        - --cpu=100m
        - --extra-cpu=1m
        - --memory=130Mi
        - --extra-memory=2Mi
        - --threshold=5
        - --deployment=kube-prometheus-exporter-kube-state
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gcr.io/google_containers/addon-resizer:1.7
        imagePullPolicy: IfNotPresent
        name: exporter-kube-state-addon-resizer
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 30Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-29T17:27:47Z
    lastUpdateTime: 2018-10-29T17:27:47Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1