apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-29T17:24:32Z
  generation: 1
  labels:
    app: prometheus-operator
    chart: prometheus-operator-0.0.29
    heritage: Tiller
    operator: prometheus
    release: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
  resourceVersion: "4151"
  selfLink: /apis/extensions/v1beta1/namespaces/monitoring/deployments/prometheus-operator
  uid: 7fb1eb26-db9f-11e8-868c-b26230958cf1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prometheus-operator
      operator: prometheus
      release: prometheus-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-operator
        operator: prometheus
        release: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.20.0
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.20.0
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-29T17:24:36Z
    lastUpdateTime: 2018-10-29T17:24:36Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-10-29T17:24:32Z
    lastUpdateTime: 2018-10-29T17:24:36Z
    message: ReplicaSet "prometheus-operator-5cd488b98b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1