apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-10-29T17:26:19Z
  labels:
    app: kube-prometheus-grafana
    chart: grafana-0.0.37
    heritage: Tiller
    release: kube-prometheus
  name: kube-prometheus-grafana
  namespace: monitoring
  resourceVersion: "6112"
  selfLink: /api/v1/namespaces/monitoring/services/kube-prometheus-grafana
  uid: bfd6d683-db9f-11e8-868c-b26230958cf1
spec:
  clusterIP: 10.0.70.67
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: kube-prometheus-grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 168.62.62.22