apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-10-29T17:26:20Z
  labels:
    operated-alertmanager: "true"
  name: alertmanager-operated
  namespace: monitoring
  resourceVersion: "4415"
  selfLink: /api/v1/namespaces/monitoring/services/alertmanager-operated
  uid: c00c3a16-db9f-11e8-868c-b26230958cf1
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: mesh
    port: 6783
    protocol: TCP
    targetPort: 6783
  selector:
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}